### ISSUE TITLE
Usage with async actions

### ISSUE THREAD

**Issue by dkourilov** [mihar-22/preact-hooks-unistore#3]
Hey Rahim,

To continue https://github.com/developit/unistore/issues/136#issuecomment-552726395, here is the problem I'm currently facing with async functions and `useAction`. 

I'm trying to realize what `useAction` should look like for async actions. Say for some reasons I don't want to use `await` statement for any Promises inside `useAction` to finally return the state, and instead is looking to somehow update the state asynchronously.

The pattern I have in mind is to return the state from `useAction` as usual for any state updates before the Promises, and use `state = store.getState(); /* update state */; store.setState(state)` in Promise `then/finally`. To some extent, this looks ugly to me, and in case you were thinking on any clear pattern to minimize the code boilerplate and improve readability for async functions, I'll greatly appreciate your feedback.

Let me know if you need a pseudocode or even more concrete TS example.

**Comment by mihar-22** [comment]
Hey @dkourilov,

If I understand correctly you're trying to understand how Promises work with `useAction`? `useAction` supports promises directly.

```js
const performAsyncOperation = async ({ count }) => {
  // perform some stuff ...
  return { count: count + 1 } // here we update the state.
}

const asyncAction = useAction(performAsyncOperation)

asyncAction() // call it or do whatever.

// Promise works the same as async just resolve the new state.
const somePromise = ({ count }) => new Promise((resolve, reject) => {
  resolve({ count : count + 1 })
})

const action = useAction(somePromise)

action() // call it.
```

Hope that helps. `useAction` just returns a Unistore action. You can read here https://github.com/developit/unistore/#usage.

**Comment by mihar-22** [comment]
If you already have a Promise object then it could look like this.

```js
// Let's say somePromise exists
const action = useAction(somePromise.then(response => {
  // do some stuff ...
  const newCount = response.count + 1
  return { count: newCount } // update state.
})

action() // call it.

// If somePromise already resolves the new state then just like async function pass it in.
const action = useAction(somePromise)

action() // call it.
``` 

Weird example but just giving you an idea of how to do it.

**Comment by dkourilov** [comment]
Awesome, this is exactly an example I was looking for. Everything is clear now, thanks for your help!
