### ISSUE TITLE
Is IE11 supported?

### ISSUE THREAD

**Issue by noradium** [mihar-22/preact-hooks-unistore#4]
I'm sorry for my poor English
I want to use this package on IE11 , but following error has occured
```
SCRIPT1002: Syntax error
```
due to using arrow functions in dist/hooks.modern.js 
(src is https://github.com/mihar-22/preact-hooks-unistore/blob/master/src/index.js#L10)

browserslist in package.json includes ie11, so I think it'll be better if I change microbundle -f option  `modern,umd` to `es,umd`
How about this?
I look forward to your reply.

**Comment by mihar-22** [comment]
Hey @noradium, did you try using the `umd` bundle? It's located at `dist/hooks.umd.js`. The modern bundle isn't for IE 11. How you integrate and use the `umd` bundle depends on your build process and tools so hard for me to help further. Microbundle should be running Babel over the `umd` bundle so if there is arrow functions in that file then there is an issue.

What will the change you suggested do? 

Thanks :)

**Comment by noradium** [comment]
Sorry to forget to write about build tools.
I use webpack + babel, so it bundles hooks.modern.js
Should I use webpack's resolve.alias options and alias `@preact-hooks/unistore` to `dist/hooks.umd.js`?

**Comment by mihar-22** [comment]
If you're bundling this using Webpack then you need to tell Babel that it should transpile this library. By default Babel excludes all node modules, so you can add the following to your Babel config.

`exclude: /node_modules\/(?![@preact-hooks])/`

If you have other packages you need to transpile then do the following

`exclude: /node_modules\/(?![@preact-hooks|anotherPackage])/`

**Comment by noradium** [comment]
I understand. It works!
What I do is
1. Add `exclude: /node_modules\/(?![@preact\-hooks])/` to babel-loader config in webpack.config.js
2. Rename .babel.js to babel.config.js. (I also overlooked this. Because of Babel 7 config change, .babel.js ignores exclude option. https://babeljs.io/docs/en/v7-migration-api#config-changes )

Thanks for your help.
