### ISSUE TITLE
shallowEquals false negative when property value is falsy

### ISSUE THREAD

**Issue by danielweck** [mihar-22/preact-hooks-unistore#5]
https://github.com/mihar-22/preact-hooks-unistore/blob/4be35da25a94fc3d9e9396ebb5db87d52e59f6c2/src/shallowEqual.js#L8

if `objB[keysA[i]] ` is falsy (empty string `‘’`, zero `0`, boolean `false` etc.) the comparison incorrectly returns false.

**Comment by mihar-22** [comment]
Thanks @danielweck for letting me know, fixed in the new release (1.1.2)
