### ISSUE TITLE
Actions that needs store

### ISSUE THREAD

**Issue by MeloJR** [mihar-22/preact-hooks-unistore#6]
Hi, I'm using this library and I have a question. If I want to use an action that use the store what is the best way to achieve it? Maybe using useStore and passing it to the action?
I need the store to make some asyncs actions (to retrieve the state after the async operation) and to call other actions inside one action.
Thank you!

**Comment by mihar-22** [comment]
Hey @MeloJR I guess you could do something like this:

```js
const asyncAction1 = async ({ someValue }) => {
  // do some async work here.
 const result = await something(someValue);
  // return state update
  return { result };
};

const asyncAction2 = async (state) => {
  // get result of `asyncAction1`
  const { result } = await asyncAction1(state);
  // do something with the result (maybe call another action)
  const newResult = await something(result);
  // return state update
  return { result: newResult };
};
```

**Comment by MeloJR** [comment]
Yeah, but it is possible that the state changes after the async action, so it is necessary a way to read it. In the unistore docs, there is an example where an action calls `store.getState()` to update its value. The store is available in that function because the connect method accepts an object or a function that receives the store.
Also, it is possible that the action wants to store some partial information, for example, before loading data and after loading data. Without the store it is impossilbe to achieve that in one action call.

**Comment by mihar-22** [comment]
Sure in that case you can work with the `useStore` hook. I guess there'd be 3 main ways you can access the store inside an action:

**Option 1**

```js
function App() {
  const store = useStore();
  
  const myAction = useAction((state) => {
    // Access store here.
  });
}
```

**Option 2 - preferred**

```js
const someAction = (store) => (state) => {
  // Access store here.
};

function App() {
  const store = useStore();
  
  const myAction = useAction(someAction(store));
}
```

**Option 3**

```js
function App() {
  const myAction = useAction((state) => {
    const store = useStore();

    // ...
  });
}
```
